'use strict';

const KEYWORD_SCORE_MAX = 40;
const SEMANTIC_SCORE_MAX = 60;
const TOTAL_SCORE_MAX = 100;
const MAX_INPUT_LENGTH = 5000;
const MAX_LRU_CACHE_SIZE = 1000;

module.exports = {
  KEYWORD_SCORE_MAX,
  SEMANTIC_SCORE_MAX,
  TOTAL_SCORE_MAX,
  MAX_INPUT_LENGTH,
  MAX_LRU_CACHE_SIZE
};
